[package]
name = "kademlia-dht"
version = "0.1.0"
authors = ["f0lg0 <folgonileonardo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.9.5"
hex = "0.4.3"
